services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - saturno_network

networks:
  saturno_network:
    external: true
